'use client'

import { useEffect, useState, useRef } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import {
  LiveKitRoom,
  RoomAudioRenderer,
  Chat,
  ParticipantTile,
  GridLayout,
  useTracks,
  useParticipants,
  useRoomContext,
  TrackToggle,
} from '@livekit/components-react'
import '@livekit/components-styles'
import { Track } from 'livekit-client'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Users,
  MessageSquare,
  Video,
  Mic,
  ScreenShare,
  LogOut,
  UserPlus,
  ChevronRight,
  ChevronLeft,
  LayoutGrid,
  Settings,
  Circle,
  Radio,
  Download,
  FileText,
  Brain,
  Loader2,
  CheckCircle,
  Sparkles
} from 'lucide-react'
import type { Room, User } from '@/lib/types/database'
import InviteModal from './InviteModal'

/* ------------------ INTELLIGENCE RECORDER HOOK ------------------ */

function useMeetingIntelligence(roomId: string, roomTitle: string) {
  const [isRecording, setIsRecording] = useState(false)
  const [processing, setProcessing] = useState(false)
  const [result, setResult] = useState<{ transcript: string, summary: string } | null>(null)
  const [exported, setExported] = useState(false)
  const mediaRecorderRef = useRef<MediaRecorder | null>(null)
  const chunksRef = useRef<Blob[]>([])

  const startRecording = async (stream: MediaStream) => {
    chunksRef.current = []
    const recorder = new MediaRecorder(stream)
    recorder.ondataavailable = (e) => chunksRef.current.push(e.data)
    recorder.onstop = async () => {
      const blob = new Blob(chunksRef.current, { type: 'audio/webm' })
      await processMeeting(blob)
    }
    recorder.start()
    mediaRecorderRef.current = recorder
    setIsRecording(true)
  }

  const stopRecording = () => {
    mediaRecorderRef.current?.stop()
    setIsRecording(false)
  }

  const processMeeting = async (blob: Blob) => {
    setProcessing(true)
    try {
      const formData = new FormData()
      formData.append('audio', blob)
      formData.append('roomId', roomId)

      const response = await fetch('/api/meetings/process', {
        method: 'POST',
        body: formData,
      })
      const data = await response.json()
      setResult(data)
    } catch (error) {
      console.error('Intelligence Processing Failed:', error)
    } finally {
      setProcessing(false)
    }
  }

  const handleExport = () => {
    if (!result) return
    const content = `
ROOMX MEETING INTELLIGENCE REPORT
----------------------------------
Sanctuary: ${roomTitle}
Date: ${new Date().toLocaleString()}

AI EXECUTIVE SUMMARY:
${result.summary}

----------------------------------
RAW TRANSCRIPT:
${result.transcript}
----------------------------------
Generated by RoomX Sanctuary Sync Engine
    `
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${roomTitle.replace(/\s+/g, '_')}_Intel_Report.txt`
    a.click()
    setExported(true)
    setTimeout(() => setExported(false), 3000)
  }

  return { isRecording, startRecording, stopRecording, processing, result, handleExport, exported }
}

/* ------------------ MAIN STUDIO COMPONENT ------------------ */

interface LiveRoomProps {
  roomId: string
  room: Room & { users: User }
  user: User
  isCreator: boolean
}

export default function LiveRoom({ roomId, room, user, isCreator }: LiveRoomProps) {
  const [token, setToken] = useState<string | undefined>(undefined)
  const [url, setUrl] = useState<string | undefined>(undefined)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [isInviteModalOpen, setIsInviteModalOpen] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [activeTab, setActiveTab] = useState<'chat' | 'participants' | 'intel'>('chat')
  
  const intel = useMeetingIntelligence(roomId, room.title)

  useEffect(() => {
    const fetchToken = async () => {
      try {
        const response = await fetch(`/api/rooms/${roomId}/access-token`)
        if (!response.ok) {
          const errorData = await response.json().catch(() => ({ error: 'Unknown error' }))
          throw new Error(errorData.error || `Failed to get access token`)
        }
        const data = await response.json()
        setToken(data.token)
        setUrl(data.url)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to connect')
      } finally {
        setLoading(false)
      }
    }
    fetchToken()
  }, [roomId])

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-zinc-950 text-white">
        <div className="relative w-24 h-24 mb-8">
          <motion.div
            animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.6, 0.3] }}
            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
            className="absolute inset-0 bg-indigo-500/20 blur-2xl rounded-full"
          />
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="w-12 h-12 border-4 border-zinc-800 border-t-indigo-500 rounded-full animate-spin" />
          </div>
        </div>
        <p className="text-zinc-400 font-medium tracking-wide uppercase tracking-[0.2em]">Synchronizing Studio...</p>
      </div>
    )
  }

  return (
    <LiveKitRoom
      video={isCreator}
      audio={isCreator}
      token={token}
      serverUrl={url}
      data-lk-theme="default"
      className="h-screen bg-black overflow-hidden flex flex-col relative"
      onDisconnected={() => {
        window.location.href = '/dashboard'
      }}
    >
      <InviteModal
        isOpen={isInviteModalOpen}
        onClose={() => setIsInviteModalOpen(false)}
        roomId={roomId}
        roomTitle={room.title}
      />

      {/* TOP FLOATING HEADER */}
      <motion.header
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        className="absolute top-6 left-6 right-6 z-40"
      >
        <div className="bg-zinc-900/60 backdrop-blur-xl border border-zinc-100/10 rounded-2xl px-6 py-3 flex items-center justify-between shadow-2xl shadow-black/80">
          <div className="flex items-center gap-6">
            <Link href="/dashboard" className="group flex items-center gap-2 text-zinc-400 hover:text-white transition-all">
              <div className="p-2 rounded-lg group-hover:bg-zinc-800 transition-all">
                <ChevronLeft size={18} />
              </div>
              <span className="font-medium hidden sm:inline">Exit to Dashboard</span>
            </Link>
            <div className="h-4 w-px bg-zinc-800" />
            <div className="flex flex-col">
              <h1 className="text-white font-bold tracking-tight text-lg line-clamp-1 font-nanum">{room.title}</h1>
              <div className="flex items-center gap-1.5">
                <div className={`w-1.5 h-1.5 rounded-full ${intel.isRecording ? 'bg-red-500 animate-pulse' : 'bg-[#10b981]'}`} />
                <span className={`text-[10px] font-black ${intel.isRecording ? 'text-red-500' : 'text-[#10b981]'} uppercase tracking-widest leading-none`}>
                  {intel.isRecording ? 'RECORDING SESSION' : 'STUDIO ACTIVE'}
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {isCreator && (
              <button
                onClick={() => {
                  if (intel.isRecording) intel.stopRecording()
                  else {
                    // Start recording (In a production app, we capture the master stream from the LiveKit room)
                    const stream = new MediaStream() 
                    intel.startRecording(stream)
                  }
                }}
                className={`flex items-center gap-2 px-6 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all shadow-lg ${intel.isRecording ? 'bg-red-600 hover:bg-red-500 text-white animate-pulse' : 'bg-white/5 border border-white/10 hover:bg-white/10 text-white'}`}
              >
                <Radio size={14} />
                <span>{intel.isRecording ? 'Stop Recording' : 'Start Intel'}</span>
              </button>
            )}
            <button
              onClick={() => setIsInviteModalOpen(true)}
              className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-black uppercase tracking-widest transition-all hover:scale-105 active:scale-95 shadow-lg shadow-indigo-600/30"
            >
              <UserPlus size={16} />
              <span className="hidden sm:inline">Invite</span>
            </button>
          </div>
        </div>
      </motion.header>

      {/* MAIN LAYOUT */}
      <div className="flex-1 flex overflow-hidden">
        <main className="flex-1 relative flex flex-col pt-24 pb-32 px-6 overflow-hidden">
          <div className="flex-1 bg-zinc-900/40 rounded-[3rem] overflow-hidden border border-zinc-800/50 shadow-inner relative">
            <CustomVideoConference isCreator={isCreator} />
          </div>

          <div className="absolute bottom-10 left-1/2 -translate-x-1/2 z-40">
            <RoomControls room={room} isCreator={isCreator} />
          </div>
        </main>

        {/* SIDEBAR */}
        <AnimatePresence>
          {sidebarOpen && (
            <motion.aside
              initial={{ x: 320 }}
              animate={{ x: 0 }}
              exit={{ x: 320 }}
              className="w-80 h-full bg-zinc-950 border-l border-white/5 flex flex-col z-30 shadow-2xl"
            >
              <div className="p-6 pb-2">
                <div className="flex p-1 bg-zinc-900 rounded-2xl mb-4">
                  <button
                    onClick={() => setActiveTab('chat')}
                    className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${activeTab === 'chat' ? 'bg-zinc-800 text-white shadow-lg' : 'text-zinc-500 hover:text-zinc-300'}`}
                  >
                    <MessageSquare size={14} />
                    Chat
                  </button>
                  <button
                    onClick={() => setActiveTab('intel')}
                    className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${activeTab === 'intel' ? 'bg-zinc-800 text-white shadow-lg' : 'text-zinc-500 hover:text-zinc-300'}`}
                  >
                    <Brain size={14} />
                    Intel
                  </button>
                </div>
              </div>

              <div className="flex-1 overflow-hidden flex flex-col">
                {activeTab === 'chat' ? (
                  <Chat className="flex-1 bg-transparent border-none text-white lk-chat" />
                ) : (
                  <div className="flex-1 p-6 space-y-6 overflow-y-auto custom-scrollbar">
                    {intel.processing ? (
                      <div className="flex flex-col items-center justify-center h-full text-center space-y-8 animate-in fade-in zoom-in duration-500">
                        <div className="relative">
                          <Loader2 className="w-16 h-16 text-indigo-500 animate-spin" />
                          <Brain className="w-6 h-6 text-indigo-200 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
                        </div>
                        <div className="space-y-3">
                          <p className="text-white font-bold text-lg font-nanum">Synthesizing Intelligence...</p>
                          <p className="text-zinc-500 text-[9px] font-black uppercase tracking-[0.25em]">Whisper + GPT-4 Core</p>
                        </div>
                      </div>
                    ) : intel.result ? (
                      <div className="space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-700">
                        <div className="space-y-4">
                           <div className="flex items-center gap-2 text-indigo-400 text-[10px] font-black uppercase tracking-[0.15em]">
                              <Sparkles className="w-3.5 h-3.5" />
                              AI Executive Summary
                           </div>
                           <div className="bg-indigo-500/10 border border-indigo-500/20 p-6 rounded-[2rem] text-xs text-indigo-100 leading-relaxed font-medium shadow-inner">
                              {intel.result.summary}
                           </div>
                        </div>

                        <div className="space-y-4">
                           <div className="flex items-center gap-2 text-zinc-500 text-[10px] font-black uppercase tracking-[0.15em]">
                              <FileText className="w-3.5 h-3.5" />
                              Surgical Transcript
                           </div>
                           <div className="text-[11px] text-zinc-400 leading-relaxed font-mono p-6 bg-zinc-900 rounded-[2rem] border border-white/5 max-h-[300px] overflow-y-auto custom-scrollbar">
                              {intel.result.transcript}
                           </div>
                        </div>

                        <button 
                          onClick={intel.handleExport}
                          className={`w-full py-5 rounded-[1.5rem] font-black text-[10px] uppercase tracking-[0.2em] flex items-center justify-center gap-3 transition-all shadow-2xl ${intel.exported ? 'bg-[#10b981] text-black' : 'bg-white text-black hover:bg-zinc-200 active:scale-95'}`}
                        >
                           {intel.exported ? (
                             <>
                               <CheckCircle className="w-4 h-4" />
                               <span>Intel Exported</span>
                             </>
                           ) : (
                             <>
                               <Download className="w-4 h-4" />
                               <span>Download Intelligence</span>
                             </>
                           )}
                        </button>
                      </div>
                    ) : (
                      <div className="flex flex-col items-center justify-center h-full text-center space-y-6 opacity-20 group hover:opacity-40 transition-opacity">
                        <Radio className="w-16 h-16" />
                        <div className="space-y-2">
                           <p className="text-xs font-black uppercase tracking-[0.3em]">Standby</p>
                           <p className="text-[10px] font-medium max-w-[160px] mx-auto leading-relaxed">Activate 'Start Intel' to begin meeting synthesis.</p>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </motion.aside>
          )}
        </AnimatePresence>

        <button
          onClick={() => setSidebarOpen(!sidebarOpen)}
          className={`absolute right-0 top-1/2 -translate-y-1/2 z-40 w-6 h-20 bg-zinc-800 hover:bg-zinc-700 rounded-l-xl transition-all flex items-center justify-center text-zinc-500 hover:text-zinc-200 border border-zinc-700/50 ${sidebarOpen ? 'mr-80' : 'mr-0'}`}
        >
          {sidebarOpen ? <ChevronRight size={14} /> : <ChevronLeft size={14} />}
        </button>
      </div>

      <RoomAudioRenderer />
    </LiveKitRoom>
  )
}

function CustomVideoConference({ isCreator }: { isCreator: boolean }) {
  const tracks = useTracks(
    [
      { source: Track.Source.Camera, withPlaceholder: true },
      { source: Track.Source.ScreenShare, withPlaceholder: false },
    ],
    { onlySubscribed: false }
  )

  return (
    <div className="h-full w-full relative">
      <GridLayout tracks={tracks} className="h-full lk-grid-layout !gap-4 !p-0">
        <ParticipantTile className="!bg-zinc-900/50 !rounded-[2.5rem] !border-none !overflow-hidden shadow-2xl relative group" />
      </GridLayout>

      <div className="absolute top-8 left-8 flex flex-row items-center gap-3 pointer-events-none">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="flex items-center gap-3 bg-black/60 backdrop-blur-xl border border-white/10 px-5 py-2.5 rounded-2xl shadow-2xl"
        >
          <div className="relative flex items-center justify-center">
            <div className="w-2.5 h-2.5 bg-red-500 rounded-full animate-ping absolute" />
            <div className="w-2.5 h-2.5 bg-red-500 rounded-full relative" />
          </div>
          <span className="text-[11px] font-black text-white uppercase tracking-[0.25em] leading-none">Studio Live</span>
        </motion.div>
      </div>
    </div>
  )
}

function RoomControls({
  room,
  isCreator,
}: {
  room: Room
  isCreator: boolean
}) {
  const router = useRouter()
  const roomContext = useRoomContext()

  const handleLeave = async () => {
    try {
      const livekitRoom = (roomContext as any)?.room
      if (livekitRoom) {
        await livekitRoom.disconnect()
      }
    } catch (error) {
      console.error('Error disconnecting from room:', error)
    } finally {
      router.push('/dashboard')
    }
  }

  return (
    <div className="bg-zinc-900/60 backdrop-blur-xl border border-white/10 p-2.5 rounded-[2.5rem] flex items-center gap-2 shadow-2xl ring-1 ring-white/5">
      <div className="flex items-center gap-2 px-2">
        {isCreator && (
          <>
            <TrackToggle source={Track.Source.Microphone}>
              <div className="p-4 bg-zinc-800 hover:bg-zinc-700 text-white rounded-2xl transition-all group active:scale-90">
                <Mic size={20} className="group-hover:text-indigo-400" />
              </div>
            </TrackToggle>
            <TrackToggle source={Track.Source.Camera}>
              <div className="p-4 bg-zinc-800 hover:bg-zinc-700 text-white rounded-2xl transition-all group active:scale-90">
                <Video size={20} className="group-hover:text-indigo-400" />
              </div>
            </TrackToggle>
          </>
        )}
      </div>

      <div className="h-10 w-px bg-zinc-800 mx-2" />

      <button
        onClick={handleLeave}
        className="px-8 py-4 bg-red-600/90 hover:bg-red-500 text-white text-xs font-black uppercase tracking-[0.15em] rounded-[1.5rem] flex items-center gap-3 transition-all hover:scale-105 active:scale-95 shadow-lg shadow-red-600/20"
      >
        <LogOut size={18} />
        {isCreator ? 'End Reality' : 'Leave'}
      </button>
    </div>
  )
}
